comment:
  layout: "diff, files"
  behavior: default
  require_changes: no

coverage:
  range: 70..100
  round: down
  precision: 2

  status:
    project:
      default:
        target: 90%
        threshold: 2%
        branches:
          - master
      dev:
        target: 85%
        threshold: 5%
        branches:
          - dev
    patch:
      default:
        target: 90%
        branches:
          - master
      dev:
        target: 85%
        branches:
          - dev
    changes: no
